### ISSUE TITLE
A few qustions about commands

### ISSUE THREAD

**Issue by kquinsland** [phord/Jarvis#21]
Hi!

Thanks a ton for your work on this. I am working on porting your work to ESPHome and have managed to get the basics working: I can request the motor move to a preset.

I was wondering if there was a way to inquire about certain things rather than SET them. Almost all of the commands you've documented cover SETTING/CLEARING things.

How does the remote get the motor controller to respond with the height? I have used your notes to decode the height ... when it's transmitted. I want to get the motor controller to send this information on command, though.

I can keep spamming the `WAKE` `0x29` command and this will light the remote buttons up. The screen will be blank for a few seconds. I suspect that it's waiting for a height report and - after some timeout period of a few seconds - the remote falls back to just displaying the "fully" logo. It will display the logo until I stop spamming the WAKE commands.

Likewise, is there a way to inquire about the units without having to issue the `0x0E` command?

**Comment by maraid** [comment]
Hi @kquinsland,

I think I can answer these to you.

_How does the remote get the motor controller to respond with the height?_

My experience is that the controlbox will never shut up really. If you send any command it'll spam a couple dozen of height reports back to you. Thus the initial 0x00 empty message. If you don't get anything back from it, then there's probably something wrong with the communication. Check the wiring.


_Is there a way to inquire about the units without having to issue the 0x0E command?_

Try 0x07. I spent some time reverse engineering more commands. The controlbox answers to 0x07 with:

0x25 - PresetRaw1 
0x26 - PresetRaw2
0x27 - PresetRaw3
0x28 - PresetRaw4
0x0E - Units 
0x19 - TouchMode
0x17 - KillMode (Anti-collision enabled)
0x1D - Sensitivity

Raw presets are just motor positions, they have to be converted to units.

Sorry for the self-advertisement but you can find more information about extra commands in [the project](https://github.com/maraid/Jarvis) I'm building:

**Comment by kquinsland** [comment]
Few extra delays, but I've finally gotten my stuff out: https://github.com/kquinsland/fully_jarvis_esphome

I've starred / followed your repo @maraid. Looking forward to a simpler ESPHome component that uses UART only... which - hopefully - should solve some of the issues I have in my own code.

**Comment by maraid** [comment]
Hi! 
Good to hear that you haven't given up. Feel free to take anything from what I've done. I cannot access the repo you linked, is it private maybe?

I'm not planning on creating a proper ESPHome component and it's kind of hacky right now as you can see in the [yaml](https://github.com/maraid/Jarvis/blob/master/jarvis.yaml).  I might create a better HA card because it is pretty basic right now.
![image](https://user-images.githubusercontent.com/24621799/171988530-77c1c4be-647c-4858-867d-5cb2d003ca25.png)

Good luck with your project and let me know if I can be of any help.

**Comment by kquinsland** [comment]
> . I cannot access the repo you linked, is it private maybe?

It was! Thanks for catching that :).

> I'm not planning on creating a proper ESPHome component

Sorry to hear that. You should re-consider as it's not much more work beyond what you've already done to get the c++/h files included. Really, it's just some python which helps ESPHome understand how to validate the yaml and how to pass off the sensor/entity IDs to your code.

Feel free to use the esphome component in my repo as a starting point.  I got some help from this guy on the ESPHome discord and used the `desky` component as a reference of sorts: https://github.com/ssieb/custom_components/tree/master/components/desky

-----

Looking at your yaml, what's the difference between these two:

```yaml
  - platform: template
    name: "$name Height"
    id: height_number
    optimistic: false
    min_value: 1
    max_value: 1800
    step: 10
    set_action:
      - lambda: (*reinterpret_cast<JarvisDesk*>(id(desk))).move(x);
  - platform: template
    name: "$name Offset"
    id: offset_number
    optimistic: true
    min_value: 1
    max_value: 1800
    step: 1
    set_action:
      - lambda: (*reinterpret_cast<JarvisDesk*>(id(desk))).setOffset(x);
 ```

Does the 'move' command work precisely? That's the biggest "i want to improve" from my current implementation: https://github.com/kquinsland/fully_jarvis_esphome/blob/main/components/fully_jarvis_cb2c/fully_jarvis_cb2c.cpp#L154
